//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ContactUsInfoMetadata))]
    public partial class ContactUsInfo
    {
        class ContactUsInfoMetadata
        {
            [Required(ErrorMessage = null, ErrorMessageResourceType = typeof(Resources.Labels), ErrorMessageResourceName = "Required")]
            [Display(Name = "رقم الهاتف")]
            public string Phone1 { get; set; }
            [Display(Name = "رقم الهاتف 2")]
            public string Phone2 { get; set; }

            [Required(ErrorMessage = null, ErrorMessageResourceType = typeof(Resources.Labels), ErrorMessageResourceName = "Required")]
            [Display(Name = "رقم الجوال")]
            public string Mobile1 { get; set; }
            [Display(Name = "رقم الجوال2")]
            public string Mobile2 { get; set; }

            [Required(ErrorMessage = null, ErrorMessageResourceType = typeof(Resources.Labels), ErrorMessageResourceName = "Required")]
            [Display(Name = "البريد الالكتروني")]
            public string Email1 { get; set; }
            [Display(Name = "البريد الالكتروني 2")]
            public string Email2 { get; set; }
            [Display(Name = "حساب السكايب")]
            public string Skype1 { get; set; }
            [Display(Name = "حساب السكايب 2")]
            public string Skype2 { get; set; }
            public string FaceBook { get; set; }
            public string Twitter { get; set; }
            public string Google { get; set; }
            public string Linkedin { get; set; }
            public string Pinterest { get; set; }
            public string Instagram { get; set; }
            [Display(Name = "خريطة جوجل")]
            public string GoogleMap { get; set; }
            [Display(Name = "العنوان")]
            public string Address { get; set; }
            [Display(Name = "أوقات الدوام")]
            public string Info { get; set; }
            [Display(Name = "العنوان انجليزي")]
            public string AddressEn { get; set; }
            [Display(Name = "المزيد انجليزي")]
            public string InfoEn { get; set; }

 

        }
    }
}
