//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ContactUMetadata))]
    public partial class ContactU
    {
        class ContactUMetadata
        {
       
            [Required(ErrorMessage = null, ErrorMessageResourceType = typeof(Resources.Labels), ErrorMessageResourceName = "Required")]
            [Display(Name = "الاسم")]
            public string Name { get; set; }
            [EmailAddress(ErrorMessage = null, ErrorMessageResourceType = typeof(Resources.Labels), ErrorMessageResourceName = "EmailAddress")]
            [Display(Name = "البريد الالكتروني")]
            public string Email { get; set; }

            [Required(ErrorMessage = null, ErrorMessageResourceType = typeof(Resources.Labels), ErrorMessageResourceName = "Required")]
            [Display(Name = "العنوان")]
            public string Title { get; set; }

            [Display(Name = "تاريخ الإضافة")]
            public DateTime Date { get; set; }

            [Display(Name = "الملخص")]
            public string Summary { get; set; }

            [Display(Name = "ملاحظات")]
            public string Notes { get; set; }

        }
    }
}
