//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(LawyerMetadata))]
    public partial class Lawyer
    {
        class LawyerMetadata
        {
       
            [Required(ErrorMessage = null, ErrorMessageResourceType = typeof(Resources.Labels), ErrorMessageResourceName = "Required")]
            [Display(Name = "الاسم")]
            public string Name { get; set; }
            [Display(Name = "الجامعة")]
            public string JobTitle { get; set; }
            [Display(Name = "عن المحامي")]
            public string About { get; set; }
            [Display(Name = "الصورة")]
            public string Image { get; set; }
            public string FaceBook { get; set; }
            public string Twitter { get; set; }
            public string Google { get; set; }
            public string LinkedIn { get; set; }
            public string Pinterest { get; set; }
            public string Instagram { get; set; }
            public string Skype { get; set; }
            [Display(Name = "تاريخ الإضافة")]
            public DateTime Date { get; set; }

        }
    }
}
