//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(PageMetadata))]
    public partial class Page
    {
        class PageMetadata
        {
            [Display(Name = "رقم الخبر")]
            public int id { get; set; }
                     
            [Display(Name = "النوع")]
            public int catId { get; set; }
    
            [Required(ErrorMessage = null, ErrorMessageResourceType = typeof(Resources.Labels), ErrorMessageResourceName = "Required")]
            [Display(Name = "العنوان")]
            public string Title { get; set; }
            [Display(Name = "المخلص")]
            public string Summary { get; set; }
            [Display(Name = "التفاصيل")]
            public string Details { get; set; }
            [Display(Name = "الصورة")]
            public string ImageName { get; set; }
          
            [Display(Name = "تاريخ الإضافة")]
            public DateTime Date { get; set; }
          
        }
    }
}
