//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(SliderMetadata))]
    public partial class Slider
    {
        class SliderMetadata
        {
  
  
            [Required(ErrorMessage = null, ErrorMessageResourceType = typeof(Resources.Labels), ErrorMessageResourceName = "Required")]
            [Display(Name = "العنوان")]
            public string Title { get; set; }
            [Display(Name = "المخلص")]
            public string Summary { get; set; }
            [Url(ErrorMessage = null, ErrorMessageResourceType = typeof(Resources.Labels), ErrorMessageResourceName = "URL")]
            [Display(Name = "الرابط")]
            public string URL { get; set; }

            [Display(Name = "الصورة")]
            public string Image { get; set; }
            [Display(Name = "تاريخ الإضافة")]
            public DateTime Date { get; set; }
            [Display(Name = "فتح في إطار جديد؟")]
            public bool NewWindow { get; set; }

        }
    }
}
