//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AmjadEntities : DbContext
    {
        public AmjadEntities()
            : base("name=AmjadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adv> Advs { get; set; }
        public virtual DbSet<AdvPosition> AdvPositions { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<ContactUsCategory> ContactUsCategories { get; set; }
        public virtual DbSet<ContactUsInfo> ContactUsInfoes { get; set; }
        public virtual DbSet<Counter> Counters { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<ImagesCategory> ImagesCategories { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsCategory> NewsCategories { get; set; }
        public virtual DbSet<NewsComment> NewsComments { get; set; }
        public virtual DbSet<PagesCategory> PagesCategories { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<SuperAccount> SuperAccounts { get; set; }
        public virtual DbSet<SuperPageCategory> SuperPageCategories { get; set; }
        public virtual DbSet<SuperPermission> SuperPermissions { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<VideosCategory> VideosCategories { get; set; }
        public virtual DbSet<Lawyer> Lawyers { get; set; }
        public virtual DbSet<SuperPage> SuperPages { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
    }
}
