//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public int ID { get; set; }
        public Nullable<int> CatId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public Nullable<int> UserIdDelete { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Notes { get; set; }
    
        public virtual ContactUsCategory ContactUsCategory { get; set; }
        public virtual SuperAccount SuperAccount { get; set; }
    }
}
