//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUsInfo
    {
        public int Id { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Skype1 { get; set; }
        public string Skype2 { get; set; }
        public string FaceBook { get; set; }
        public string Twitter { get; set; }
        public string Google { get; set; }
        public string Linkedin { get; set; }
        public string Pinterest { get; set; }
        public string Instagram { get; set; }
        public string GoogleMap { get; set; }
        public string Address { get; set; }
        public string Info { get; set; }
        public string AddressEn { get; set; }
        public string InfoEn { get; set; }
        public Nullable<int> UserIdAdd { get; set; }
        public Nullable<int> UserIdUpdate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual SuperAccount SuperAccount { get; set; }
        public virtual SuperAccount SuperAccount1 { get; set; }
    }
}
