//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ID { get; set; }
        public Nullable<int> CatId { get; set; }
        public string ImageName { get; set; }
        public string Title { get; set; }
        public Nullable<int> LangId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<int> UserIdAdd { get; set; }
        public Nullable<int> UserIdUpdate { get; set; }
        public Nullable<int> UserIdDelete { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ImagesCategory ImagesCategory { get; set; }
        public virtual Language Language { get; set; }
    }
}
