//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewsCategory()
        {
            this.News = new HashSet<News>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Name { get; set; }
        public string EName { get; set; }
        public Nullable<bool> ShowTitle { get; set; }
        public Nullable<bool> ShowSummary { get; set; }
        public Nullable<bool> ShowDetails { get; set; }
        public Nullable<bool> ShowImageName { get; set; }
        public Nullable<bool> ShowCategory { get; set; }
        public Nullable<bool> ShowFileName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UserIdAdd { get; set; }
        public Nullable<int> UserIdUpdate { get; set; }
        public Nullable<int> UserIdDelete { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> ShowVideoName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
        public virtual SuperAccount SuperAccount { get; set; }
        public virtual SuperAccount SuperAccount1 { get; set; }
        public virtual SuperAccount SuperAccount2 { get; set; }
    }
}
