//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.NewsComments = new HashSet<NewsComment>();
        }
    
        public int id { get; set; }
        public Nullable<int> catId { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Details { get; set; }
        public string ImageName { get; set; }
        public string FileName { get; set; }
        public string VideoName { get; set; }
        public Nullable<int> LangId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<int> UserIdAdd { get; set; }
        public Nullable<int> UserIdUpdate { get; set; }
        public Nullable<int> UserIdDelete { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsBest { get; set; }
        public Nullable<int> Views { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual NewsCategory NewsCategory { get; set; }
        public virtual SuperAccount SuperAccount { get; set; }
        public virtual SuperAccount SuperAccount1 { get; set; }
        public virtual SuperAccount SuperAccount2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsComment> NewsComments { get; set; }
    }
}
