//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagesCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PagesCategory()
        {
            this.Pages = new HashSet<Page>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> ShowTitle { get; set; }
        public Nullable<bool> ShowSummary { get; set; }
        public Nullable<bool> ShowDetails { get; set; }
        public Nullable<bool> ShowFileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page> Pages { get; set; }
    }
}
