//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int id { get; set; }
        public Nullable<int> catId { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Details { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> LangId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UserIdAdd { get; set; }
        public Nullable<int> UserIdUpdate { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual PagesCategory PagesCategory { get; set; }
        public virtual SuperAccount SuperAccount { get; set; }
        public virtual SuperAccount SuperAccount1 { get; set; }
    }
}
