//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperPermission
    {
        public int ID { get; set; }
        public Nullable<int> SuperAccountId { get; set; }
        public Nullable<int> SuperPageId { get; set; }
        public Nullable<int> UserIdAdd { get; set; }
    
        public virtual SuperAccount SuperAccount { get; set; }
        public virtual SuperPage SuperPage { get; set; }
    }
}
