//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amjad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuperPage()
        {
            this.SuperPermissions = new HashSet<SuperPermission>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public string Icon { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual SuperPageCategory SuperPageCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuperPermission> SuperPermissions { get; set; }
    }
}
